development:
  adapter: postgresql
  encoding: unicode
  database: rails-aws-upload-template-development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: rails-aws-upload-template-test
  host: localhost
  pool: 5
