development:
  secret_key_base: secret_key_base
  aws:
    access_key_id: "AKIAJUVHOZL7MEGZTNLQ"
    secret_access_key: "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"
    s3_bucket_name: "ywca-website"
test:
  secret_key_base: secret_key_base
  aws:
    access_key_id: "AKIAJUVHOZL7MEGZTNLQ"
    secret_access_key: "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"
    s3_bucket_name: "ywca-website"
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws:
    access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
    s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
